### ISSUE TITLE
concurrent_hash_map tests fail

### ISSUE THREAD

**Issue by kilobyte** [pmem/libpmemobj-cpp#350] opened 2019-06-27 12:39 UTC
These three tests fail:
        147 - concurrent_hash_map_0_drd
        148 - concurrent_hash_map_0_helgrind
        152 - concurrent_hash_map_rehash_0_helgrind
Tested on two machines:
 * Debian buster (+ pmdk-1.6 from Debian/experimental): gcc-8, valgrind 3.14, kernel 5.1.14
 * Debian unstable + gcc-9 and pmdk-1.6: valgrind 3.14, kernel 5.2-rc6

with same errors.

(ex-pman fail is unrelated: it doesn't like hardcopy terminals w/o addressable cursor; probably too obscure case to bother fixing.)

Logs: [buster](https://angband.pl/tmp/objcpp.ab-desk.txt), [unstable](https://angband.pl/tmp/objcpp.valinor.txt).

**Comment by igchor** [comment] 2019-11-06 14:02
This was probably caused by the same reason as https://github.com/pmem/libpmemobj-cpp/issues/469
I will close this for now.

**Closed by igchor** 2019-11-06 14:02 UTC
